%  Copyright (c) 2021 Franka Emika GmbH - All Rights Reserved
%  This file is subject to the terms and conditions defined in the file
%  'LICENSE' , which is part of this package

function mex_mxfunction(src)

src_full_path = which(src);
src_full_home_path = fileparts(src_full_path);

warnStruct = warning('off', 'MATLAB:mex:GccVersion_link');

project_root = fileparts(which('init_franka_matlab'));
franka_matlab_configs = load('franka_matlab_configs');
libfranka_path = franka_matlab_configs.libfranka_path;

if exist(fullfile(project_root,'CMakeFiles'),'dir')
    rmdir(fullfile(project_root,'CMakeFiles'),'s');
end

disp([newline,'<=== Mexing ',src,' ===>',newline]);

if ispc 
    
    mex_string = ['mex COPTIMFLAGS="/O2 /Oy" ', ...
              '''-L', fullfile(libfranka_path, 'build'), ''' ',...
              '''-L', fullfile(libfranka_path, 'build/examples'), ''' ',...
              '-lfranka -lexamples_common -lmx -lmex ',...
              '-I', fullfile(libfranka_path, 'include'), ' ',...
              '-I', fullfile(libfranka_path, 'examples'), ' ',...
              '-I', fullfile(franka_matlab_configs.eigen_dir,'../../include'), ' ',...
              fullfile(src_full_home_path, src),...
              ' -outdir ', src_full_home_path]; 
elseif isunix 
    
    mex_string = ['mex  CXXFLAGS=''-fPIC -O3 -fno-loop-optimize -std=c++14 -Wno-format-overflow'' ', ...
                       'LINKLIBS='' -Wl,-rpath,',matlabroot,...
                       '/bin/glnxa64 -Wl,-rpath ',...
                       libfranka_path,'/build -L"',...
                       matlabroot,'/bin/glnxa64" ',...
                       '-L"',libfranka_path,'/build" ',...
                       '-L"',libfranka_path,'/build/examples" ',...
                       '-lfranka -lexamples_common -lmx -lmex '' ', ...
                       '-I"',libfranka_path,'/include/" ',...
                       '-I"',libfranka_path,'/examples/" ',...
                       '-I"',get_eigen_install_path_linux(), '" ',...
                       src_full_home_path,'/',src,...
                       ' -outdir ',src_full_home_path,'/'];
end          
               
evalin('base',mex_string);

warning(warnStruct);

end