clear
clc

m=sym('m',[1,7]);
l_x=sym('l_x',[1,7]);
l_y=sym('l_y',[1,7]);
l_z=sym('l_z',[1,7]);
L_xx=sym('L_xx',[1,7]);
L_xy=sym('L_xy',[1,7]);
L_xz=sym('L_xz',[1,7]);
L_yz=sym('L_yz',[1,7]);
L_yy=sym('L_yy',[1,7]);
L_zz=sym('L_zz',[1,7]);

name="c++RNE";

if name == "sympybotics"
    %% sympybotics toolbox full parameters
    parms=[L_xx;L_xy;L_xz;L_yy;L_yz;L_zz;l_x;l_y;l_z;m];
    opt_params=reshape(parms,70,1);
elseif name=="RNE"
    %% RNE full parameters
    W=sym(ones(1,70));
    W(1:10:end)=m;
    W(2:10:end)=l_x;W(3:10:end)=l_y;W(4:10:end)=l_z;
    W(5:10:end)=L_xx;W(6:10:end)=L_yy;W(7:10:end)=L_zz;
    W(8:10:end)=L_yz;
    W(9:10:end)=L_xz;
    W(10:10:end)=L_xy;
    parms=W.';
    opt_params=reshape(parms,70,1);
else
    %% c++ RNE full parameters
    W=sym(ones(1,70));
    W(1:10:end)=m;
    W(2:10:end)=l_x;W(3:10:end)=l_y;W(4:10:end)=l_z;
    W(5:10:end)=L_xx;W(6:10:end)=L_xy;W(7:10:end)=L_yy;
    W(8:10:end)=L_xz;
    W(9:10:end)=L_yz;
    W(10:10:end)=L_zz;
    parms=W.';
    opt_params=reshape(parms,70,1);
end


%% Base parameter vector generated by the sympybotics toolbox
basepar=[L_zz(1) + L_yy(2);
     L_xx(2) - L_yy(2) + L_yy(3) + 79*l_z(3)/125 + 6241*m(3)/62500 + 426649*m(4)/4000000 + 426649*m(5)/4000000 + 426649*m(6)/4000000 + 426649*m(7)/4000000;
     L_xy(2);
     L_xz(2);
     L_yz(2);
     L_zz(2) + L_yy(3) + 79*l_z(3)/125 + 6241*m(3)/62500 + 426649*m(4)/4000000 + 426649*m(5)/4000000 + 426649*m(6)/4000000 + 426649*m(7)/4000000;
     l_x(2);
     l_y(2) - l_z(3) - 79*m(3)/250 - 79*m(4)/250 - 79*m(5)/250 - 79*m(6)/250 - 79*m(7)/250;
     L_xx(3) - L_yy(3) + L_yy(4) - 1089*m(4)/160000;
     L_xy(3) + 33*l_z(4)/400;
     L_xz(3);
     L_yz(3);
     L_zz(3) + L_yy(4) + 1089*m(4)/160000 + 1089*m(5)/80000 + 1089*m(6)/80000 + 1089*m(7)/80000;
     l_x(3) + 33*m(4)/400 + 33*m(5)/400 + 33*m(6)/400 + 33*m(7)/400;
     l_y(3) - l_z(4);
     L_xx(4) - L_yy(4) + L_yy(5) + 96*l_z(5)/125 + 562599*m(5)/4000000 + 562599*m(6)/4000000 + 562599*m(7)/4000000;
     L_xy(4) + 33*l_z(5)/400 + 99*m(5)/3125 + 99*m(6)/3125 + 99*m(7)/3125;
     L_xz(4);
     L_yz(4);
     L_zz(4) + L_yy(5) + 96*l_z(5)/125 + 617049*m(5)/4000000 + 617049*m(6)/4000000 + 617049*m(7)/4000000;
     l_x(4) - 33*m(5)/400 - 33*m(6)/400 - 33*m(7)/400;
     l_y(4) + l_z(5) + 48*m(5)/125 + 48*m(6)/125 + 48*m(7)/125;
     L_xx(5) - L_yy(5) + L_yy(6) + 121*m(7)/15625;
     L_xy(5);
     L_xz(5);
     L_yz(5);
     L_zz(5) + L_yy(6) + 121*m(7)/15625;
     l_x(5);
     l_y(5) - l_z(6);
     L_xx(6) - L_yy(6) + L_yy(7) - 121*m(7)/15625;
     L_xy(6) + 11*l_z(7)/125;
     L_xz(6);
     L_yz(6);
     L_zz(6) + L_yy(7) + 121*m(7)/15625;
     l_x(6) + 11*m(7)/125;
     l_y(6) - l_z(7);
     L_xx(7) - L_yy(7);
     L_xy(7);
     L_xz(7);
     L_yz(7);
     L_zz(7);
     l_x(7);
     l_y(7)];

P=zeros(43,70);
for k=1:43
    for i=1:70
        P(k,i)=diff(basepar(k),opt_params(i));
    end
end
